---
driver:
  name: ec2
  aws_ssh_key_id: hyd
  region: ap-south-1
  availability_zone: a
  subnet_id: subnet-8bbc9de3
  instance_type: t2.micro
  image_id: ami-0cb892447fb9d327e
  security_group_ids: ["sg-a2eefbcd"]
  retryable_tries: 120

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.9

verifier:
  name: inspec

transport:
  ssh_key: C:\Users\Salim\Downloads\hyd.pem

platforms:
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[learn_chef_httpd::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
